
services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./source:/home/node/app/source
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: auwwwth
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev